# Generated by Django 3.1.7 on 2021-02-22 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('date_of_born', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотка игрока')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название команды')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.visitor')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team', verbose_name='Команда'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, verbose_name='Коммент')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата коммента')),
                ('for_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Игрок')),
            ],
        ),
    ]
